# parameters.py

# VAR AUTO ENCODER PARAMETERS
IM_WIDTH = 160
IM_HEIGHT = 80
LATENT_DIM = 95

# ACTOR-CRITIC NETWORK PARAMETERS
OBSERVATION_DIM = 100
ACTION_DIM = 2

# HYPERPARAMETERS
ACTION_STD_INIT = 0.2
LEARNING_RATE = 1e-4
BATCH_SIZE = 1
POLICY_CLIP = 0.2
GAMMA = 0.99
LAMBDA = 0.95
NO_OF_ITERATIONS = 15
SEED = 0

# TRAINING PARAMETERS
TOTAL_TIMESTEPS = 2e6
EPISODE_LENGTH = 7500
TEST_TIMESTEPS = 1e6

# SIMULATION PARAMETERS 
TOWN = 'Town02'
CAR_NAME = 'model3'
NUMBER_OF_VEHICLES = 30
NUMBER_OF_PEDESTRIAN = 10
CONTINUOUS_ACTION = True
VISUAL_DISPLAY = False

# PATHS
VAR_AUTO_MODEL_PATH = 'VAE'
PPO_MODEL_PATH = 'PPO_MODEL'
CHECKPOINT_PATH = 'CHECKPOINTS'
TEST_IMAGES = 'TEST_IMAGES'

CHECKPOINT_LOAD = False
